theme: jekyll-theme-cayman
title: Artificial Intelligence, Manage Money, Save Money
description: Blah blah
repository: michael-brooks.github.io/aisaver
baseurl: ""
url: "http://aisaver.co.uk"
gems:
  - jekyll-feed
  - jekyll-sitemap